# docker-compose.dev.yml for local development
version: '3.8'
services:
  web:
    build:
      context: .
      target: runner # Build up to the runner stage for a production-like image
    volumes:
      -.:/app # Bind mount for hot-reloading during development
    ports:
      - "3000:3000" # Map host port 3000 to container port 3000
    command: npm run dev # Start the Next.js development server
    environment:
      NODE_ENV: development