# docker-compose.prod.yml
version: '3.8'
services:
  web:
    image: ${REGISTRY}/${IMAGE_NAME}:latest
    container_name: fba-frontend
    ports:
      - "3000:3000"
    restart: unless-stopped
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3