
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${BUILD_TARGET:-runner} # Default to runner for production, can be overridden for dev
    container_name: fbafrontend
    restart: unless-stopped # Use unless-stopped for both dev and prod
    env_file:
      - .env
    environment:
      NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
      NEXT_PUBLIC_WS_BACKEND_URL: ${NEXT_PUBLIC_WS_BACKEND_URL}
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
