version: "3.9"
services:
  nextjs:
    container_name: nextjs_frontend
    build:
      context: .
      target: runner
    ports:
      - "3000:3000"
    restart: unless-stopped
    env_file:
      - .env